M48
; DRILL file {KiCad 7.0.7} date Wed Mar 27 23:33:30 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-27T23:33:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1180
%
G90
G05
T1
X2.9Y-1.4
X2.9Y-5.1
X6.7Y-1.4
X6.7Y-5.1
T2
X6.038Y-5.62
X6.71Y-5.62
T0
M30
